### ISSUE TITLE
Table view is cutoff

### ISSUE THREAD

**Issue by nickpollari** [QuantStack/ipysheet#109]
Putting a sheet inside of a VBox with a max height and scroll actually cuts off the data in the table (both along x and y) and cannot scroll to see the data.

```python

import pandas as pd
import numpy as np
import ipywidgets
import ipysheet

data = np.random.randn(500,20)

cols = ["Field %s" % (str(x + 1)) for x in range(data.shape[1])]

dataframe = pd.DataFrame(data, columns=cols)
sheet2 = ipysheet.from_dataframe(dataframe)
ipywidgets.VBox([sheet2], layout={'max_height' : '400px', 'overflow_y' : 'auto'})
```

**Comment by martinRenou** [comment]
Thanks for filling this issue :) I'll take a look at it

**Comment by martinRenou** [comment]
I tried with this code (it is basically the same but adding the scroll bar to the sheet instead of adding it to the VBox):
```python
import pandas as pd
import numpy as np
import ipywidgets
import ipysheet

data = np.random.randn(500,20)

cols = ["Field %s" % (str(x + 1)) for x in range(data.shape[1])]

dataframe = pd.DataFrame(data, columns=cols)
sheet2 = ipysheet.from_dataframe(dataframe)
sheet2.layout = {'max_height' : '400px', 'overflow_y' : 'auto'}
ipywidgets.VBox([ipywidgets.IntSlider(), sheet2])
```
And this is the result:
![test_ipysheet](https://user-images.githubusercontent.com/21197331/56229628-a4e10e00-607a-11e9-866f-5a9cd41f5007.png)

Basically, when scrolling down we see that the sheet rows are not rendered... Disabling virtual rendering as proposed in this PR #11 fixes this issue (at least partially). The virtual rendering is not triggered when scrolling down. I don't feel comfortable disabling virtual rendering, Handsontable is already quite slow, we don't want to slow it down more.

**Comment by martinRenou** [comment]
There must be a way to tweak the CSS so that it renders like in the Handsontable documentation https://handsontable.com/docs/6.2.2/demo-scrolling.html. Not being a CSS expert makes it a hard task for me.
It would be cleaner to fix it through CSS than disabling the virtual rendering.

**Comment by martinRenou** [comment]
I think this issue is mainly due to the fact that the table cannot be resized using Handsontable. You can see equivalent issues if you reduce the size of the window containing the sheet.

**Comment by nickpollari** [comment]
That sounds like a deal breaker for this table

**Comment by martinRenou** [comment]
I totally agree

**Comment by martinRenou** [comment]
There are ongoing discussions for switching to another table implementation #61.

**Comment by martinRenou** [comment]
It would be possible to always render the entire sheet, playing with the [renderallrow attribute](https://handsontable.com/docs/6.2.2/Options.html#renderAllRows), so that we do not rely on the virtual-scrolling anymore. And we would put the table in a resizable and scrollable container.

This would slow down ipysheet, but it would work.

**Comment by SylvainCorlay** [comment]
@nickpollari @martinRenou I am fixing this in #121, working around the way handsontable operates:

Here is the result with your example:

![ipysheet-resize](https://user-images.githubusercontent.com/2397974/57523514-75de5500-7325-11e9-9e04-c7fb13b1c31f.gif)

Now ipysheet tables will by default take as much vertical space as necessary to display all rows. If a fixed height is set, scrollbars will be displayed to allow scrolling on all the data.

**Comment by martinRenou** [comment]
Perfect! So Handsontable needs a constant-size container only when rendering for the first time?

**Comment by SylvainCorlay** [comment]
> Perfect! So Handsontable needs a constant-size container only when rendering the first time?

It does not really need a constant size container, but their logic is a bit broken. Will detail on another thread.
