### ISSUE TITLE
How many `Cell`s should I make?

### ISSUE THREAD

**Issue by krey** [QuantStack/ipysheet#24]
What's the recommended number of cells to have?

Like, a Cell object could represent the entire sheet, or I could make one Cell object for each row or one for literally every cell.

What's best for performance?

**Comment by maartenbreddels** [comment]
Hi Krey,

It depends, if you update 1 cell every time, separate Cell objects will be better (only that state will be synced). If you have a big matrix you set each time, a cell_range would (matrix) would be faster, otherwise there will be sync events for each cell value that is changed vs a single sync with a 2d list.  
Hope that answers your question.

cheers,

Maarten
